const editorial = {
 uk: {city:'ДНІПРО, УКРАЇНА',demo:'ПОРТФОЛІО / ДЕМО',nav:['Обрати сервіс','Майстерня','Запис'],headline:'Що потрібно\nвашому авто?',intro:'Регулярне ТО, незвичний звук чи сигнал на панелі? Почнімо з того, що вас турбує.',browse:'Каталог послуг',selector:'ОБЕРІТЬ НАПРЯМ',selectorNote:'Схема допомагає обрати послугу. Вона не визначає несправність.',selected:'ОБРАНО',choose:'Обговорити цю послугу',short:['Діагностика','Планове ТО','Підвіска','Гальма','Двигун','Колеса'],serviceTitle:'Сервіс по суті.',serviceSubtitle:'Відкрийте напрям — подивіться, з чим можемо допомогти.',serviceLink:'Додати до звернення',workshop:'УСЕ ПОЧИНАЄТЬСЯ З ОГЛЯДУ',workshopTitle:'Розібратися.\nУзгодити.\nЗробити.',photoNote:'Ілюстративне зображення майстерні',ticket:'ЗАКАЗ-НАРЯД / ЯК ЦЕ ПРАЦЮЄ',ticketNote:'Роботи й кошторис — після вашого погодження.',reviewLabel:'ГОЛОС КЛІЄНТА / ПРИКЛАД',previous:'Попередній відгук',next:'Наступний відгук',faqTitle:'Питання перед\nзаїздом.',bookingLabel:'СЕРВІСНЕ ЗВЕРНЕННЯ',bookingTitle:'Авто в деталях.\nЗапис у два кроки.',bookingNote:'Демонстрація: заявки не надсилаються, час не бронюється.',steps:['Автомобіль','Контакт','Готово'],nextStep:'Далі: контакт',back:'Назад',check:'Перевірити звернення',summary:'ВАШЕ ЗВЕРНЕННЯ',emptyCar:'Автомобіль ще не вказано',emptyService:'Напрям ще не обрано',restart:'Нове звернення',done:'Звернення готове.',doneText:'У реальному сервісі тут починається діалог з майстром. У демоверсії дані залишаються лише на цій сторінці.',telegram:'Чернетка для Telegram',telegramNote:'Можна скопіювати текст. Реальний контакт СТО не підключений.',footer:'Автосервіс у Дніпрі. Демонстраційний проєкт.',contactNote:'Адреса та графік будуть додані для реальної майстерні.',mainLabel:'Основна навігація',openMenu:'Відкрити меню',closeMenu:'Закрити меню',edit:'Редагувати авто',stepLabel:'Крок',diagram:'Схематичне зображення автомобіля'},
 en: {city:'DNIPRO, UKRAINE',demo:'PORTFOLIO / DEMO',nav:['Find your service','Workshop','Enquiry'],headline:'What does\nyour car need?',intro:'Routine maintenance, an unusual noise or a dashboard light? Let’s start with what brought you here.',browse:'Service directory',selector:'CHOOSE A SERVICE',selectorNote:'This diagram helps you choose a service. It does not diagnose a fault.',selected:'SELECTED',choose:'Discuss this service',short:['Diagnostics','Maintenance','Suspension','Brakes','Engine','Wheels'],serviceTitle:'Service, made clear.',serviceSubtitle:'Open a category to see how we can help.',serviceLink:'Add to my enquiry',workshop:'IT ALL STARTS WITH AN INSPECTION',workshopTitle:'Understand.\nAgree.\nRepair.',photoNote:'Illustrative workshop image',ticket:'WORK ORDER / HOW IT WORKS',ticketNote:'Work and cost agreed with you before we begin.',reviewLabel:'CUSTOMER VOICE / SAMPLE',previous:'Previous review',next:'Next review',faqTitle:'Before you\ndrive in.',bookingLabel:'SERVICE ENQUIRY',bookingTitle:'Your car in detail.\nTwo simple steps.',bookingNote:'Demonstration: enquiries are not sent and no time is booked.',steps:['Vehicle','Contact','Ready'],nextStep:'Next: contact details',back:'Back',check:'Check my enquiry',summary:'YOUR ENQUIRY',emptyCar:'Vehicle not specified yet',emptyService:'Service not selected yet',restart:'New enquiry',done:'Your enquiry is ready.',doneText:'At a real workshop, this is where the conversation with a technician starts. In this demonstration your details stay on this page only.',telegram:'Telegram message draft',telegramNote:'Copy the text if you like. No real workshop contact is connected.',footer:'Auto service in Dnipro. Portfolio demonstration.',contactNote:'Address and opening hours would be added for a real workshop.',mainLabel:'Main navigation',openMenu:'Open menu',closeMenu:'Close menu',edit:'Edit vehicle',stepLabel:'Step',diagram:'Schematic view of a car'}
};
let language = new URL(location.href).searchParams.get('lang') === 'en' ? 'en' : 'uk';
let selectedService = 1, activeFilter = 0, reviewIndex = 0, bookingStep = 0;
let savedForm = {}, openServices = ['1'], openFaq = [], menuOpen = false;
const safe = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const lines = value => safe(value).replaceAll('\n','<br>');
const arrow = '<span aria-hidden="true">↗</span>';
const carDrawing = `<svg viewBox="0 0 620 270" aria-hidden="true" fill="none" xmlns="http://www.w3.org/2000/svg"><defs><pattern id="grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M30 0H0V30" stroke="currentColor" stroke-opacity=".08"/></pattern></defs><rect width="620" height="270" fill="url(#grid)"/><path d="M47 194v-39l24-17 60-10 60-70h179l78 70 97 19 25 25v22h-39m-97 0H193m-92 0H47" stroke="currentColor" stroke-width="3" stroke-linejoin="round"/><path d="m155 125 49-56h76v56H155Zm140-56h65l65 56H295V69Z" fill="currentColor" fill-opacity=".07" stroke="currentColor" stroke-width="2"/><path d="M301 135v47m-23-46h-18m83 0h-18M71 151h50m390 10h38M52 175h49m391 0h64" stroke="currentColor" stroke-width="2"/><circle cx="148" cy="189" r="47" fill="#eeede7" stroke="currentColor" stroke-width="3"/><circle cx="148" cy="189" r="29" stroke="currentColor" stroke-width="2"/><circle cx="148" cy="189" r="10" stroke="currentColor" stroke-width="2"/><circle cx="482" cy="189" r="47" fill="#eeede7" stroke="currentColor" stroke-width="3"/><circle cx="482" cy="189" r="29" stroke="currentColor" stroke-width="2"/><circle cx="482" cy="189" r="10" stroke="currentColor" stroke-width="2"/><path d="M117 189h62m-31-31v62m303-31h62m-31-31v62M23 248h574" stroke="currentColor" stroke-opacity=".2"/><path d="M433 141h47v23h-47z" stroke="currentColor" stroke-opacity=".4" stroke-width="2"/><path d="M213 199h179" stroke="currentColor" stroke-dasharray="5 5" stroke-opacity=".4"/></svg>`;
function captureState(){
 const form=document.getElementById('enquiry');
 if(form){savedForm=Object.fromEntries(new FormData(form));savedForm.consent=form.elements.consent.checked;}
 openServices=[...document.querySelectorAll('[data-service-row][open]')].map(e=>e.dataset.serviceRow);
 openFaq=[...document.querySelectorAll('[data-faq][open]')].map(e=>e.dataset.faq);
}
function render(){
 const t=copy[language],e=editorial[language];
 document.documentElement.lang=language;document.title=t.title;
 document.querySelector('meta[name=description]').content=t.description;
 document.getElementById('app').innerHTML=`
 <a class="skip" href="#main">${t.skip}</a>
 <header class="header wrap"><a class="wordmark" href="#" aria-label="AutoCare">AUTO<span>CARE</span><i aria-hidden="true">↗</i></a><span class="header-city mono">${e.city}</span><nav aria-label="${e.mainLabel}" class="nav ${menuOpen?'is-open':''}" id="nav">${e.nav.map((n,i)=>`<a href="#${['selector','workshop','contact'][i]}">${n}</a>`).join('')}</nav><div class="header-actions"><div class="language-switch" aria-label="Language"><button type="button" data-lang="uk" aria-pressed="${language==='uk'}">UA</button><span>/</span><button type="button" data-lang="en" aria-pressed="${language==='en'}">EN</button></div><button class="menu" type="button" aria-controls="nav" aria-expanded="${menuOpen}" aria-label="${menuOpen?e.closeMenu:e.openMenu}" data-menu><span></span><span></span></button></div></header>
 <main id="main">
 <section class="opening wrap" id="selector"><div class="opening-copy"><p class="mono demo-label"><span class="status-dot"></span>${e.demo}</p><h1>${lines(e.headline)}</h1><p class="opening-intro">${e.intro}</p><a class="directory-link" href="#services">${e.browse}${arrow}</a><div class="opening-bottom mono"><span>AUTOCARE /</span><span>UA — EN</span></div></div>
 <div class="service-console"><div class="console-heading mono"><span>${e.selector}</span><span>AC—06</span></div><div class="vehicle" role="group" aria-label="${e.diagram}">${carDrawing}${[[0,72,41],[1,50,18],[2,36,70],[3,24,70],[4,81,52],[5,77,77]].map(([s,x,y])=>`<button type="button" class="hotspot ${selectedService===s?'selected':''}" style="--x:${x}%;--y:${y}%" data-pick="${s}" aria-label="${e.short[s]}" aria-pressed="${selectedService===s}">${s+1}</button>`).join('')}</div><div class="service-buttons" role="group" aria-label="${e.selector}">${e.short.map((s,i)=>`<button type="button" data-pick="${i}" aria-pressed="${selectedService===i}"><span class="mono">0${i+1}</span>${s}</button>`).join('')}</div><div class="console-result" aria-live="polite"><span class="mono result-index">0${selectedService+1}</span><div><span class="mono selected-label">${e.selected}</span><h2>${t.services[selectedService][0]}</h2><p>${t.services[selectedService][1]}</p></div></div><a class="solid" href="#contact" data-book-service="${selectedService}">${e.choose}${arrow}</a><p class="console-note">${e.selectorNote}</p></div></section>
 <section class="directory wrap" id="services"><div class="directory-heading"><h2>${e.serviceTitle}</h2><p>${e.serviceSubtitle}</p></div><div class="directory-toolbar"><div class="filters" role="group" aria-label="${t.navServices}">${t.filters.map((f,i)=>`<button type="button" data-filter="${i}" aria-pressed="${activeFilter===i}">${f}</button>`).join('')}</div><span class="mono" id="filter-status" role="status">${t.resultCount+t.services.filter(s=>activeFilter===0||s[2]===activeFilter).length}</span></div><div class="service-list">${t.services.map((s,i)=>({s,i})).filter(({s})=>activeFilter===0||s[2]===activeFilter).map(({s,i})=>`<details data-service-row="${i}" ${openServices.includes(String(i))?'open':''}><summary><span class="mono row-number">0${i+1}</span><h3>${s[0]}</h3><span class="row-category mono">${t.filters[s[2]]}</span><span class="plus" aria-hidden="true"></span></summary><div class="service-row-body"><p>${s[1]}</p><a href="#contact" data-book-service="${i}">${e.serviceLink}${arrow}</a></div></details>`).join('')}</div></section>
 <section class="workshop" id="workshop"><div class="workshop-photo"><img src="hero.png" width="1672" height="941" alt="${e.photoNote}" loading="lazy"><div class="workshop-overlay"><p class="mono">${e.workshop}</p><h2>${lines(e.workshopTitle)}</h2></div><span class="photo-caption mono">AUTOCARE / DNIPRO</span></div><div class="work-order"><div class="ticket-top mono"><span>${e.ticket}</span><span>AC /</span></div><div class="ticket-steps">${t.processItems.map((s,i)=>`<article><span class="mono">0${i+1}</span><div><h3>${s[0]}</h3><p>${s[1]}</p></div><span class="ticket-arrow" aria-hidden="true">${i===3?'✓':'↓'}</span></article>`).join('')}</div><p class="ticket-note">${e.ticketNote}</p><div class="barcode" aria-hidden="true"></div></div></section>
 <section class="trust wrap"><div class="trust-heading"><p class="mono">${e.reviewLabel}</p><div class="review-controls"><button type="button" data-review="-1" aria-label="${e.previous}">←</button><span class="mono">0${reviewIndex+1} / 03</span><button type="button" data-review="1" aria-label="${e.next}">→</button></div></div><figure aria-live="polite"><blockquote>${t.reviews[reviewIndex][0]}</blockquote><figcaption><strong>${t.reviews[reviewIndex][1]}</strong><span>${t.reviews[reviewIndex][2]}</span></figcaption></figure><p class="review-disclaimer">${t.reviewsNote}</p></section>
 <section class="booking" id="contact"><div class="wrap"><div class="booking-heading"><p class="mono">${e.bookingLabel}</p><h2>${lines(e.bookingTitle)}</h2><p>${e.bookingNote}</p></div><div class="booking-workspace"><div class="booking-main"><ol class="step-tabs" aria-label="${e.bookingLabel}">${e.steps.map((s,i)=>`<li ${bookingStep===i?'aria-current="step"':''}><span>0${i+1}</span>${s}</li>`).join('')}</ol><form id="enquiry" novalidate><div data-step="0" ${bookingStep!==0?'hidden':''}><div class="field"><label for="car">${t.car}</label><input id="car" name="car" required minlength="2" maxlength="100" placeholder="${t.carPlaceholder}"></div><div class="field"><label for="service">${t.service}</label><select id="service" name="service" required><option value="">${t.selectDefault}</option>${t.services.map((s,i)=>`<option value="${i}">${s[0]}</option>`).join('')}</select></div><div class="field"><label for="message">${t.message} <span>(${t.optional})</span></label><textarea id="message" name="message" rows="3" maxlength="600" placeholder="${t.messagePlaceholder}"></textarea></div><button type="button" class="solid" data-next>${e.nextStep}<span aria-hidden="true">→</span></button></div><div data-step="1" ${bookingStep!==1?'hidden':''}><div class="field"><label for="name">${t.name}</label><input id="name" name="name" required minlength="2" maxlength="80" autocomplete="name" placeholder="${t.namePlaceholder}"></div><div class="field"><label for="phone">${t.phone}</label><input id="phone" name="phone" type="tel" required maxlength="24" autocomplete="tel" placeholder="${t.phonePlaceholder}"></div><label class="consent"><input type="checkbox" name="consent" required><span>${t.consent}</span></label><div class="form-actions"><button type="button" class="back-button" data-back>← ${e.back}</button><button type="submit" class="solid">${e.check}${arrow}</button></div></div><div data-step="2" ${bookingStep!==2?'hidden':''} role="status" aria-live="polite" class="success"><span class="success-mark" aria-hidden="true">✓</span><h3>${e.done}</h3><p>${t.success}</p><p>${e.doneText}</p><button type="button" class="solid" data-telegram>${e.telegram}${arrow}</button><button type="button" class="back-button" data-restart>${e.restart}</button></div></form></div><aside class="enquiry-summary"><p class="mono">${e.summary}</p><div class="summary-car" aria-hidden="true">${carDrawing.replaceAll('id="grid"','id="summary-grid"').replaceAll('url(#grid)','url(#summary-grid)')}</div><strong id="summary-car"></strong><p id="summary-service"></p><button class="edit-enquiry" type="button" data-edit>${e.edit} ↗</button><div class="summary-telegram"><span class="mono">TELEGRAM /</span><p>${e.telegramNote}</p><button type="button" class="text-link" data-telegram>${e.telegram}${arrow}</button></div></aside></div></div></section>
 <section class="questions wrap" id="faq"><div><p class="mono">FAQ /</p><h2>${lines(e.faqTitle)}</h2><p class="city-note">${t.city}<br>${e.contactNote}</p></div><div class="faq-list">${t.faqItems.map((f,i)=>`<details data-faq="${i}" ${openFaq.includes(String(i))?'open':''}><summary>${f[0]}<span class="plus" aria-hidden="true"></span></summary><p>${f[1]}</p></details>`).join('')}</div></section>
 </main><footer class="footer wrap"><span class="footer-wordmark">AUTOCARE<span aria-hidden="true">↗</span></span><div><p>${e.footer}</p><span class="mono">${e.demo} · ${e.city}</span></div><a href="#" class="top-link" aria-label="${t.top}">↑</a></footer>
 <dialog id="telegram-dialog" aria-labelledby="draft-title"><div class="dialog-heading"><h3 id="draft-title">${t.draftTitle}</h3><button type="button" data-close aria-label="${t.close}">×</button></div><p>${t.draftNote}</p><label class="sr-only" for="draft-text">${t.draftTitle}</label><textarea id="draft-text" rows="8" readonly></textarea><div class="dialog-actions"><button type="button" class="solid" data-copy>${t.copy}</button><button type="button" class="back-button" data-close>${t.close}</button></div><p id="copy-status" role="status" aria-live="polite"></p></dialog>`;
 const form=document.getElementById('enquiry');
 for(const[k,v]of Object.entries(savedForm)){const f=form.elements.namedItem(k);if(f){if(f.type==='checkbox')f.checked=Boolean(v);else f.value=v;}}
 updateSummary();
}
function updateSummary(){const t=copy[language],e=editorial[language],form=document.getElementById('enquiry');document.getElementById('summary-car').textContent=form.elements.car.value.trim()||e.emptyCar;const s=form.elements.service.value;document.getElementById('summary-service').textContent=s===''?e.emptyService:t.services[Number(s)][0];}
function validStep(step){const form=document.getElementById('enquiry'),t=copy[language];let fields;
 if(step===0){const car=form.elements.car;car.setCustomValidity(car.value.trim().length>=2?'':t.carError);fields=[car,form.elements.service];}
 else{const name=form.elements.name,phone=form.elements.phone,digits=phone.value.replace(/\D/g,'');name.setCustomValidity(name.value.trim().length>=2?'':t.nameError);phone.setCustomValidity(/^[+\d\s().-]+$/.test(phone.value)&&digits.length>=9&&digits.length<=15?'':t.phoneError);fields=[name,phone,form.elements.consent];}
 for(const field of fields)if(!field.reportValidity())return false;return true;
}
function moveStep(step){captureState();bookingStep=step;render();const panel=document.querySelector(`[data-step="${step}"]`);if(step<2)panel.querySelector('input').focus({preventScroll:true});else panel.querySelector('button').focus({preventScroll:true});document.querySelector('.booking-workspace').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}
document.addEventListener('input',event=>{if(event.target.closest('#enquiry')){event.target.setCustomValidity?.('');updateSummary();}});
document.addEventListener('change',event=>{if(event.target.closest('#enquiry'))updateSummary();});
document.addEventListener('submit',event=>{if(event.target.id!=='enquiry')return;event.preventDefault();if(!validStep(0)){moveStep(0);validStep(0);return;}if(validStep(1))moveStep(2);});
document.addEventListener('click',async event=>{
 const button=event.target.closest('button,a');if(!button)return;
 if(button.dataset.lang){if(language===button.dataset.lang)return;captureState();language=button.dataset.lang;const url=new URL(location.href);url.searchParams.set('lang',language);history.replaceState(null,'',url);render();document.querySelector(`[data-lang="${language}"]`).focus({preventScroll:true});}
 else if(button.hasAttribute('data-menu')){menuOpen=!menuOpen;document.getElementById('nav').classList.toggle('is-open',menuOpen);button.setAttribute('aria-expanded',String(menuOpen));button.setAttribute('aria-label',menuOpen?editorial[language].closeMenu:editorial[language].openMenu);}
 else if(button.closest('#nav')){menuOpen=false;document.getElementById('nav').classList.remove('is-open');document.querySelector('[data-menu]').setAttribute('aria-expanded','false');document.querySelector('[data-menu]').setAttribute('aria-label',editorial[language].openMenu);}
 else if(button.hasAttribute('data-pick')){captureState();selectedService=Number(button.dataset.pick);savedForm.service=String(selectedService);if(bookingStep===2)bookingStep=0;render();document.querySelector(`.service-buttons [data-pick="${selectedService}"]`).focus({preventScroll:true});}
 else if(button.hasAttribute('data-book-service')){event.preventDefault();captureState();selectedService=Number(button.dataset.bookService);savedForm.service=String(selectedService);bookingStep=0;render();document.getElementById('contact').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});history.replaceState(null,'',location.pathname+location.search+'#contact');}
 else if(button.hasAttribute('data-filter')){captureState();activeFilter=Number(button.dataset.filter);render();document.querySelector(`[data-filter="${activeFilter}"]`).focus({preventScroll:true});}
 else if(button.hasAttribute('data-review')){captureState();reviewIndex=(reviewIndex+Number(button.dataset.review)+3)%3;render();document.querySelector(`[data-review="${button.dataset.review}"]`).focus({preventScroll:true});}
 else if(button.hasAttribute('data-next')){if(validStep(0))moveStep(1);}
 else if(button.hasAttribute('data-back')||button.hasAttribute('data-edit'))moveStep(0);
 else if(button.hasAttribute('data-restart')){savedForm={};bookingStep=0;render();document.getElementById('car').focus({preventScroll:true});}
 else if(button.hasAttribute('data-telegram')){const t=copy[language],data=new FormData(document.getElementById('enquiry')),parts=[t.draftHello];for(const key of ['name','phone','car','service','message']){let value=data.get(key);if(value?.trim()){if(key==='service')value=t.services[Number(value)][0];parts.push(t[key]+': '+value.trim());}}document.getElementById('draft-text').value=parts.length>1?parts.join('\n'):t.draftDefault;document.getElementById('copy-status').textContent='';document.getElementById('telegram-dialog').showModal();}
 else if(button.hasAttribute('data-close'))document.getElementById('telegram-dialog').close();
 else if(button.hasAttribute('data-copy')){const t=copy[language];try{await navigator.clipboard.writeText(document.getElementById('draft-text').value);document.getElementById('copy-status').textContent=t.copied;}catch{document.getElementById('draft-text').focus();document.getElementById('draft-text').select();document.getElementById('copy-status').textContent=t.copyError;}}
});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&menuOpen){menuOpen=false;document.getElementById('nav').classList.remove('is-open');const button=document.querySelector('[data-menu]');button.setAttribute('aria-expanded','false');button.setAttribute('aria-label',editorial[language].openMenu);button.focus();}});
addEventListener('popstate',()=>{captureState();language=new URL(location.href).searchParams.get('lang')==='en'?'en':'uk';render();});
render();
